#!/usr/bin/env bash
set -euo pipefail

PAM_FLOW="${PAM_FLOW:-smoke}"
PAM_SERVICE="${PAM_SERVICE:-sudo}"
SECUREEYE_USER="${SECUREEYE_USER:-${TEST_USER:-test_user}}"
SECUREEYE_PASS="${SECUREEYE_PASS:-${TEST_PASS:-test_user}}"
SECUREEYE_DEVICE="${SECUREEYE_DEVICE:-${SECUREEYE_VIDEO_DEVICE:-/dev/video2}}"
RUN_ADD=0
RUN_TEST=0
INTERACTIVE_SUDO=0
