#!/usr/bin/python3
# Installation script to install secureEye
# Executed after primary apt install

# Import required modules
import fileinput
import os
import re
import subprocess
import sys
import tarfile
from shutil import rmtree, which

# Don't run unless we need to configure the install
# Will also happen on upgrade but we will catch that later on
if "configure" not in sys.argv:
	sys.exit(0)


def log(text):
	"""Print a nicely formatted line to stdout"""
	print("\n>>> " + col(1) + text + col(0) + "\n")


def handleStatus(status):
	"""Abort if a command fails"""
	if (status != 0):
		print(col(3) + "Error while running last command" + col(0))
		sys.exit(1)


def col(id):
	"""Add color escape sequences"""
	if id == 1: return "\033[32m"
	if id == 2: return "\033[33m"
	if id == 3: return "\033[31m"
	return "\033[0m"


# Create shorthand for subprocess creation
sc = subprocess.call

# If the package is being upgraded
if "upgrade" in sys.argv:
	# If preinst has made a config backup
	if os.path.exists("/tmp/secureEye_config_backup_v" + sys.argv[2] + ".ini"):
		# Get the config parser
		import configparser

		# Load th old and new config files
		oldConf = configparser.ConfigParser()
		oldConf.read("/tmp/secureEye_config_backup_v" + sys.argv[2] + ".ini")
		newConf = configparser.ConfigParser()
		newConf.read("/etc/secureEye/config.ini")

		# Go through every setting in the old config and apply it to the new file
		"""
		for section in oldConf.sections():
			for (key, value) in oldConf.items(section):
		"""

		# Write it all to file
		with open("/etc/secureEye/config.ini", "w") as configfile:
			newConf.write(configfile)

	sys.exit(0)

log("Downloading dlib")

dlib_archive = "/tmp/v19.16.tar.gz"
loader = which("wget")
LOADER_CMD = None

# If wget is installed, use that as the downloader
if loader:
	LOADER_CMD = [loader, "--tries", "5", "--output-document"]
# Otherwise, fall back on curl
else:
	loader = which("curl")
	LOADER_CMD = [loader, "--retry", "5", "--location", "--output"]

# Assemble and execute the download command
cmd = LOADER_CMD + [dlib_archive, "https://github.com/davisking/dlib/archive/v19.16.tar.gz"]
handleStatus(sc(cmd))

# The folder containing the dlib source
DLIB_DIR = None
# A regex of all files to ignore while unpacking the archive
excludes = re.compile(
	r"davisking-dlib-\w+/(dlib/(http_client|java|matlab|test/)|"
	r"(docs|examples|python_examples)|"
	r"tools/(archive|convert_dlib_nets_to_caffe|htmlify|imglab|python/test|visual_studio_natvis))"
)

# Open the archive
with tarfile.open(dlib_archive) as tf:
	for item in tf:
		# Set the destination dir if unset
		if not DLIB_DIR:
			DLIB_DIR = "/tmp/" + item.name

		# extract only files sufficient for building
		if not excludes.match(item.name):
			tf.extract(item, "/tmp")

# Delete the downloaded archive
os.unlink(dlib_archive)

log("Building dlib")

cmd = ["sudo", "python3", "setup.py", "install"]
cuda_used = False

# Compile and link dlib
try:
	sp = subprocess.Popen(cmd, cwd=DLIB_DIR, stdout=subprocess.PIPE)
except subprocess.CalledProcessError:
	print("Error while building dlib")
	raise

# Go through each line from stdout to check for CUDA usage
while sp.poll() is None:
	line = sp.stdout.readline().decode("utf-8")

	if "DLIB WILL USE CUDA" in line:
		cuda_used = True

	print(line, end="")

log("Cleaning up dlib")

# Remove the no longer needed git clone
del sp
rmtree(DLIB_DIR)

print("Temporary dlib files removed")

log("Configuring secureEye")

# Make sure to use CNN if dlib was compiled with CUDA support
for line in fileinput.input(["/etc/secureEye/config.ini"], inplace=1):
	line = line.replace("use_cnn = false", "use_cnn = " + str(cuda_used).lower())
	print(line, end="")

print("CNN saved to config, CUDA " + ("enabled" if cuda_used else "disabled"))

# Secure the secureEye folder
handleStatus(sc(["chmod 755 -R /lib/security/secureEye/"], shell=True))
handleStatus(sc(["chmod 755 -R /etc/secureEye/"], shell=True))

# Allow anyone to execute the python CLI
os.chmod("/lib/security/secureEye", 0o755)
os.chmod("/lib/security/secureEye/cli.py", 0o755)
handleStatus(sc(["chmod 755 -R /lib/security/secureEye/cli"], shell=True))
print("Permissions set")

# Make the CLI executable as secureEye
os.symlink("/lib/security/secureEye/cli.py", "/usr/local/bin/secureEye")
os.chmod("/usr/local/bin/secureEye", 0o755)
print("SecureEye command installed")

log("Adding secureEye as PAM module")

# Activate the pam-config file
handleStatus(subprocess.call(["pam-auth-update --package"], shell=True))

# Sign off
print("Installation complete.")
